# Generated by Django 6.0 on 2026-01-06 14:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskmembership',
            unique_together={('user', 'task', 'role')},
        ),
    ]
