# Generated by Django 6.0 on 2026-01-06 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_rename_taskstate_taskstatus'),
        ('tasks', '0003_rename_title_task_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskStateHistory',
            new_name='TaskStatusHistory',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='current_state',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='taskstatushistory',
            old_name='state',
            new_name='status',
        ),
    ]
