# Generated by Django 6.0 on 2026-01-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
        ('tasks', '0003_rename_title_task_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskState',
            new_name='TaskStatus',
        ),
    ]
